grails-app/domain/com/booleanworks/ring1/v1/FileItem.groovy
package com.booleanworks.ring1.v1

class FileItem {

    //static mapWith = "mongo"
    static searchable = true
    
    static mapping = {
        autoTimestamp true
    }    
    
    static hasMany = [chunks : FileChunk]
    
    static constraints = {
        fileName(nullable:false,blank:false,size:0..200) 
        virtualCanonicalPath(nullable:false,blank:false,unique:false,size:0..2000) 
        
        dateCreated(nullable:true)
        lastUpdated (nullable:true) 
        invariantUniversalUniqueId(nullable:true)
        variableUniversalUniqueId(nullable:true)        
    }
    
    String fileName 
    String virtualCanonicalPath
    
    Date dateCreated
    Date lastUpdated
    String invariantUniversalUniqueId
    String variableUniversalUniqueId
    
    def beforeInsert(){
        invariantUniversalUniqueId = new UUID(new Date().getTime(), new Random().nextLong()).toString()
        variableUniversalUniqueId = invariantUniversalUniqueId
    } 
    
    def beforeUpdate(){
        variableUniversalUniqueId = new UUID(new Date().getTime(), new Random().nextLong()).toString()
    }    
    
    public String toString()
    {
        return "FileItem[" + id + "]"
        //return "FileItem[" + id + "], " + this.properties
    }
}

grails-app/controllers/com/booleanworks/ring1/v1/FileItemController.groovy
package com.booleanworks.ring1.v1



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import grails.plugin.springsecurity.annotation.Secured

@Transactional(readOnly = true)
class FileItemController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(["hasRole('SUPER_ADMIN')"])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond FileItem.list(params), model:[fileItemInstanceCount: FileItem.count()]
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def show(FileItem fileItemInstance) {
        respond fileItemInstance
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def create() {
        respond new FileItem(params)
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def save(FileItem fileItemInstance) {
        if (fileItemInstance == null) {
            notFound()
            return
        }

        if (fileItemInstance.hasErrors()) {
            respond fileItemInstance.errors, view:'create'
            return
        }

        fileItemInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'fileItemInstance.label', default: 'FileItem'), fileItemInstance.id])
                redirect fileItemInstance
            }
            '*' { respond fileItemInstance, [status: CREATED] }
        }
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def edit(FileItem fileItemInstance) {
        respond fileItemInstance
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def update(FileItem fileItemInstance) {
        if (fileItemInstance == null) {
            notFound()
            return
        }

        if (fileItemInstance.hasErrors()) {
            respond fileItemInstance.errors, view:'edit'
            return
        }

        fileItemInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'FileItem.label', default: 'FileItem'), fileItemInstance.id])
                redirect fileItemInstance
            }
            '*'{ respond fileItemInstance, [status: OK] }
        }
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def delete(FileItem fileItemInstance) {

        if (fileItemInstance == null) {
            notFound()
            return
        }

        fileItemInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'FileItem.label', default: 'FileItem'), fileItemInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'fileItemInstance.label', default: 'FileItem'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/fileItem/_form.gsp
<%@ page import="com.booleanworks.ring1.v1.FileItem" %>



<div class="fieldcontain ${hasErrors(bean: fileItemInstance, field: 'fileName', 'error')} required">
	<label for="fileName">
		<g:message code="fileItem.fileName.label" default="File Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="fileName" maxlength="200" required="" value="${fileItemInstance?.fileName}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: fileItemInstance, field: 'virtualCanonicalPath', 'error')} required">
	<label for="virtualCanonicalPath">
		<g:message code="fileItem.virtualCanonicalPath.label" default="Virtual Canonical Path" />
		<span class="required-indicator">*</span>
	</label>
	<g:textArea name="virtualCanonicalPath" cols="40" rows="5" maxlength="2000" required="" value="${fileItemInstance?.virtualCanonicalPath}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: fileItemInstance, field: 'chunks', 'error')} ">
	<label for="chunks">
		<g:message code="fileItem.chunks.label" default="Chunks" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${fileItemInstance?.chunks?}" var="c">
    <li><g:link controller="fileChunk" action="show" id="${c.id}">${c?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="fileChunk" action="create" params="['fileItem.id': fileItemInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'fileChunk.label', default: 'FileChunk')])}</g:link>
</li>
</ul>

</div>

grails-app/views/fileItem/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileItem.label', default: 'FileItem')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
                <ckeditor:resources/>
	</head>
	<body>
		<a href="#create-fileItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-fileItem" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${fileItemInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${fileItemInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:fileItemInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/fileItem/edit.gsp
<%@ page import="com.booleanworks.ring1.v1.FileItem" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileItem.label', default: 'FileItem')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
                <ckeditor:resources/>
	</head>
	<body>
		<a href="#edit-fileItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-fileItem" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${fileItemInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${fileItemInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:fileItemInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${fileItemInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/fileItem/index.gsp
<%@ page import="com.booleanworks.ring1.v1.FileItem" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileItem.label', default: 'FileItem')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-fileItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-fileItem" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="fileName" title="${message(code: 'fileItem.fileName.label', default: 'File Name')}" />
					
						<g:sortableColumn property="virtualCanonicalPath" title="${message(code: 'fileItem.virtualCanonicalPath.label', default: 'Virtual Canonical Path')}" />
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'fileItem.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="lastUpdated" title="${message(code: 'fileItem.lastUpdated.label', default: 'Last Updated')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${fileItemInstanceList}" status="i" var="fileItemInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${fileItemInstance.id}">${fieldValue(bean: fileItemInstance, field: "fileName")}</g:link></td>
					
						<td>${fieldValue(bean: fileItemInstance, field: "virtualCanonicalPath")}</td>
					
						<td><g:formatDate date="${fileItemInstance.dateCreated}" /></td>
					
						<td><g:formatDate date="${fileItemInstance.lastUpdated}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${fileItemInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/fileItem/show.gsp
<%@ page import="com.booleanworks.ring1.v1.FileItem" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileItem.label', default: 'FileItem')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-fileItem" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-fileItem" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list fileItem">
			
				<g:if test="${fileItemInstance?.fileName}">
				<li class="fieldcontain">
					<span id="fileName-label" class="property-label"><g:message code="fileItem.fileName.label" default="File Name" /></span>
					
						<span class="property-value" aria-labelledby="fileName-label"><g:fieldValue bean="${fileItemInstance}" field="fileName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileItemInstance?.virtualCanonicalPath}">
				<li class="fieldcontain">
					<span id="virtualCanonicalPath-label" class="property-label"><g:message code="fileItem.virtualCanonicalPath.label" default="Virtual Canonical Path" /></span>
					
						<span class="property-value" aria-labelledby="virtualCanonicalPath-label"><g:fieldValue bean="${fileItemInstance}" field="virtualCanonicalPath"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileItemInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="fileItem.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${fileItemInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileItemInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="fileItem.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${fileItemInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileItemInstance?.chunks}">
				<li class="fieldcontain">
					<span id="chunks-label" class="property-label"><g:message code="fileItem.chunks.label" default="Chunks" /></span>
					
						<g:each in="${fileItemInstance.chunks}" var="c">
						<span class="property-value" aria-labelledby="chunks-label"><g:link controller="fileChunk" action="show" id="${c.id}">${c?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:fileItemInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${fileItemInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>