grails-app/domain/com/booleanworks/ring1/v1/Organization.groovy
package com.booleanworks.ring1.v1

class Organization {

    //static mapWith = "mongo"
    static searchable = true
    
    static mapping = {
        autoTimestamp true
    }    
    
    static constraints = {
        dateCreated(nullable:true)
        lastUpdated (nullable:true)
        invariantUniversalUniqueId(nullable:true)
        variableUniversalUniqueId(nullable:true)        
        
        parentOrganization(nullable:true)
        mainManager(nullable:true)
        deputyManager(nullable:true)
        
        acronym(nullable:true,blank:false,size:0..32)
        
        shortDescription(nullable:false,blank:false,size:0..200)
        longDescription(nullable:false,blank:true,size:0..4095)        
    }
    
    Date dateCreated
    Date lastUpdated
    String invariantUniversalUniqueId
    String variableUniversalUniqueId
    
    def beforeInsert(){
        invariantUniversalUniqueId = new UUID(new Date().getTime(), new Random().nextLong()).toString()
        variableUniversalUniqueId = invariantUniversalUniqueId
    } 
    
    def beforeUpdate(){
        variableUniversalUniqueId = new UUID(new Date().getTime(), new Random().nextLong()).toString()
    }     
    
    Organization parentOrganization 
    Person mainManager
    Person deputyManager
    
    String acronym
    
    String shortDescription
    String longDescription    
    
    public String toString()
    {
        return "Organization: " + shortDescription + "[" + id + "]"
    }
}

grails-app/controllers/com/booleanworks/ring1/v1/OrganizationController.groovy
package com.booleanworks.ring1.v1



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import grails.plugin.springsecurity.annotation.Secured

@Transactional(readOnly = true)
class OrganizationController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(["hasRole('SUPER_ADMIN')"])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Organization.list(params), model:[organizationInstanceCount: Organization.count()]
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def show(Organization organizationInstance) {
        respond organizationInstance
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def create() {
        respond new Organization(params)
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def save(Organization organizationInstance) {
        if (organizationInstance == null) {
            notFound()
            return
        }

        if (organizationInstance.hasErrors()) {
            respond organizationInstance.errors, view:'create'
            return
        }

        organizationInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'organizationInstance.label', default: 'Organization'), organizationInstance.id])
                redirect organizationInstance
            }
            '*' { respond organizationInstance, [status: CREATED] }
        }
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def edit(Organization organizationInstance) {
        respond organizationInstance
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def update(Organization organizationInstance) {
        if (organizationInstance == null) {
            notFound()
            return
        }

        if (organizationInstance.hasErrors()) {
            respond organizationInstance.errors, view:'edit'
            return
        }

        organizationInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Organization.label', default: 'Organization'), organizationInstance.id])
                redirect organizationInstance
            }
            '*'{ respond organizationInstance, [status: OK] }
        }
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def delete(Organization organizationInstance) {

        if (organizationInstance == null) {
            notFound()
            return
        }

        organizationInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Organization.label', default: 'Organization'), organizationInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'organizationInstance.label', default: 'Organization'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/organization/_form.gsp
<%@ page import="com.booleanworks.ring1.v1.Organization" %>



<div class="fieldcontain ${hasErrors(bean: organizationInstance, field: 'parentOrganization', 'error')} ">
	<label for="parentOrganization">
		<g:message code="organization.parentOrganization.label" default="Parent Organization" />
		
	</label>
	<g:select id="parentOrganization" name="parentOrganization.id" from="${com.booleanworks.ring1.v1.Organization.list()}" optionKey="id" value="${organizationInstance?.parentOrganization?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: organizationInstance, field: 'mainManager', 'error')} ">
	<label for="mainManager">
		<g:message code="organization.mainManager.label" default="Main Manager" />
		
	</label>
	<g:select id="mainManager" name="mainManager.id" from="${com.booleanworks.ring1.v1.Person.list()}" optionKey="id" value="${organizationInstance?.mainManager?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: organizationInstance, field: 'deputyManager', 'error')} ">
	<label for="deputyManager">
		<g:message code="organization.deputyManager.label" default="Deputy Manager" />
		
	</label>
	<g:select id="deputyManager" name="deputyManager.id" from="${com.booleanworks.ring1.v1.Person.list()}" optionKey="id" value="${organizationInstance?.deputyManager?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: organizationInstance, field: 'acronym', 'error')} ">
	<label for="acronym">
		<g:message code="organization.acronym.label" default="Acronym" />
		
	</label>
	<g:textField name="acronym" maxlength="32" value="${organizationInstance?.acronym}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: organizationInstance, field: 'shortDescription', 'error')} required">
	<label for="shortDescription">
		<g:message code="organization.shortDescription.label" default="Short Description" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="shortDescription" maxlength="200" required="" value="${organizationInstance?.shortDescription}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: organizationInstance, field: 'longDescription', 'error')} ">
	<label for="longDescription">
		<g:message code="organization.longDescription.label" default="Long Description" />
		
	</label>
	<g:textArea name="longDescription" cols="40" rows="5" maxlength="4095" value="${organizationInstance?.longDescription}"/>
</div>

grails-app/views/organization/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'organization.label', default: 'Organization')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
                <ckeditor:resources/>
	</head>
	<body>
		<a href="#create-organization" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-organization" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${organizationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${organizationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:organizationInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/organization/edit.gsp
<%@ page import="com.booleanworks.ring1.v1.Organization" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'organization.label', default: 'Organization')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
                <ckeditor:resources/>
	</head>
	<body>
		<a href="#edit-organization" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-organization" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${organizationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${organizationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:organizationInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${organizationInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/organization/index.gsp
<%@ page import="com.booleanworks.ring1.v1.Organization" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'organization.label', default: 'Organization')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-organization" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-organization" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'organization.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="lastUpdated" title="${message(code: 'organization.lastUpdated.label', default: 'Last Updated')}" />
					
						<th><g:message code="organization.parentOrganization.label" default="Parent Organization" /></th>
					
						<th><g:message code="organization.mainManager.label" default="Main Manager" /></th>
					
						<th><g:message code="organization.deputyManager.label" default="Deputy Manager" /></th>
					
						<g:sortableColumn property="acronym" title="${message(code: 'organization.acronym.label', default: 'Acronym')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${organizationInstanceList}" status="i" var="organizationInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${organizationInstance.id}">${fieldValue(bean: organizationInstance, field: "dateCreated")}</g:link></td>
					
						<td><g:formatDate date="${organizationInstance.lastUpdated}" /></td>
					
						<td>${fieldValue(bean: organizationInstance, field: "parentOrganization")}</td>
					
						<td>${fieldValue(bean: organizationInstance, field: "mainManager")}</td>
					
						<td>${fieldValue(bean: organizationInstance, field: "deputyManager")}</td>
					
						<td>${fieldValue(bean: organizationInstance, field: "acronym")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${organizationInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/organization/show.gsp
<%@ page import="com.booleanworks.ring1.v1.Organization" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'organization.label', default: 'Organization')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-organization" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-organization" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list organization">
			
				<g:if test="${organizationInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="organization.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${organizationInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${organizationInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="organization.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${organizationInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${organizationInstance?.parentOrganization}">
				<li class="fieldcontain">
					<span id="parentOrganization-label" class="property-label"><g:message code="organization.parentOrganization.label" default="Parent Organization" /></span>
					
						<span class="property-value" aria-labelledby="parentOrganization-label"><g:link controller="organization" action="show" id="${organizationInstance?.parentOrganization?.id}">${organizationInstance?.parentOrganization?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${organizationInstance?.mainManager}">
				<li class="fieldcontain">
					<span id="mainManager-label" class="property-label"><g:message code="organization.mainManager.label" default="Main Manager" /></span>
					
						<span class="property-value" aria-labelledby="mainManager-label"><g:link controller="person" action="show" id="${organizationInstance?.mainManager?.id}">${organizationInstance?.mainManager?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${organizationInstance?.deputyManager}">
				<li class="fieldcontain">
					<span id="deputyManager-label" class="property-label"><g:message code="organization.deputyManager.label" default="Deputy Manager" /></span>
					
						<span class="property-value" aria-labelledby="deputyManager-label"><g:link controller="person" action="show" id="${organizationInstance?.deputyManager?.id}">${organizationInstance?.deputyManager?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${organizationInstance?.acronym}">
				<li class="fieldcontain">
					<span id="acronym-label" class="property-label"><g:message code="organization.acronym.label" default="Acronym" /></span>
					
						<span class="property-value" aria-labelledby="acronym-label"><g:fieldValue bean="${organizationInstance}" field="acronym"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${organizationInstance?.shortDescription}">
				<li class="fieldcontain">
					<span id="shortDescription-label" class="property-label"><g:message code="organization.shortDescription.label" default="Short Description" /></span>
					
						<span class="property-value" aria-labelledby="shortDescription-label"><g:fieldValue bean="${organizationInstance}" field="shortDescription"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${organizationInstance?.longDescription}">
				<li class="fieldcontain">
					<span id="longDescription-label" class="property-label"><g:message code="organization.longDescription.label" default="Long Description" /></span>
					
						<span class="property-value" aria-labelledby="longDescription-label"><g:fieldValue bean="${organizationInstance}" field="longDescription"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:organizationInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${organizationInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>