grails-app/domain/com/booleanworks/ring1/v1/Activity.groovy
package com.booleanworks.ring1.v1

class Activity {

    //static mapWith = "mongo"
    static searchable = true
    
    static mapping = {
        autoTimestamp true
    }    
    
    
    static hasMany = [tagLinks : TagToActivityLink , personLinks :PersonToActivityLink, taskLinks :TaskToActivityLink]
    
    static constraints = {
        shortDescription(nullable:false,blank:false,size:0..200)
        longDescription(nullable:false,blank:true,size:0..4095)
        
        owner(nullable:false)
        
        realWorkHours(nullable:false,min:0.0d)
        
        dateCreated(nullable:true)
        lastUpdated (nullable:true)   
        invariantUniversalUniqueId(nullable:true)
        variableUniversalUniqueId(nullable:true)
    }
    
    String shortDescription
    String longDescription
    
    Person owner 
    
    Double realWorkHours
        
    Date dateCreated
    Date lastUpdated
    String invariantUniversalUniqueId
    String variableUniversalUniqueId
    
    def beforeInsert(){
        invariantUniversalUniqueId = new UUID(new Date().getTime(), new Random().nextLong()).toString()
        variableUniversalUniqueId = invariantUniversalUniqueId
    } 
    
    def beforeUpdate(){
        variableUniversalUniqueId = new UUID(new Date().getTime(), new Random().nextLong()).toString()
    } 
    
}

grails-app/controllers/com/booleanworks/ring1/v1/ActivityController.groovy
package com.booleanworks.ring1.v1



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import grails.plugin.springsecurity.annotation.Secured

@Transactional(readOnly = true)
class ActivityController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(["hasRole('SUPER_ADMIN')"])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Activity.list(params), model:[activityInstanceCount: Activity.count()]
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def show(Activity activityInstance) {
        respond activityInstance
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def create() {
        respond new Activity(params)
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def save(Activity activityInstance) {
        if (activityInstance == null) {
            notFound()
            return
        }

        if (activityInstance.hasErrors()) {
            respond activityInstance.errors, view:'create'
            return
        }

        activityInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'activityInstance.label', default: 'Activity'), activityInstance.id])
                redirect activityInstance
            }
            '*' { respond activityInstance, [status: CREATED] }
        }
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def edit(Activity activityInstance) {
        respond activityInstance
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def update(Activity activityInstance) {
        if (activityInstance == null) {
            notFound()
            return
        }

        if (activityInstance.hasErrors()) {
            respond activityInstance.errors, view:'edit'
            return
        }

        activityInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Activity.label', default: 'Activity'), activityInstance.id])
                redirect activityInstance
            }
            '*'{ respond activityInstance, [status: OK] }
        }
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def delete(Activity activityInstance) {

        if (activityInstance == null) {
            notFound()
            return
        }

        activityInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Activity.label', default: 'Activity'), activityInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'activityInstance.label', default: 'Activity'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/activity/_form.gsp
<%@ page import="com.booleanworks.ring1.v1.Activity" %>



<div class="fieldcontain ${hasErrors(bean: activityInstance, field: 'shortDescription', 'error')} required">
	<label for="shortDescription">
		<g:message code="activity.shortDescription.label" default="Short Description" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="shortDescription" maxlength="200" required="" value="${activityInstance?.shortDescription}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: activityInstance, field: 'longDescription', 'error')} ">
	<label for="longDescription">
		<g:message code="activity.longDescription.label" default="Long Description" />
		
	</label>
	<g:textArea name="longDescription" cols="40" rows="5" maxlength="4095" value="${activityInstance?.longDescription}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: activityInstance, field: 'owner', 'error')} required">
	<label for="owner">
		<g:message code="activity.owner.label" default="Owner" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="owner" name="owner.id" from="${com.booleanworks.ring1.v1.Person.list()}" optionKey="id" required="" value="${activityInstance?.owner?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: activityInstance, field: 'realWorkHours', 'error')} required">
	<label for="realWorkHours">
		<g:message code="activity.realWorkHours.label" default="Real Work Hours" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="realWorkHours" value="${fieldValue(bean: activityInstance, field: 'realWorkHours')}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: activityInstance, field: 'personLinks', 'error')} ">
	<label for="personLinks">
		<g:message code="activity.personLinks.label" default="Person Links" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${activityInstance?.personLinks?}" var="p">
    <li><g:link controller="personToActivityLink" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="personToActivityLink" action="create" params="['activity.id': activityInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'personToActivityLink.label', default: 'PersonToActivityLink')])}</g:link>
</li>
</ul>

</div>

<div class="fieldcontain ${hasErrors(bean: activityInstance, field: 'tagLinks', 'error')} ">
	<label for="tagLinks">
		<g:message code="activity.tagLinks.label" default="Tag Links" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${activityInstance?.tagLinks?}" var="t">
    <li><g:link controller="tagToActivityLink" action="show" id="${t.id}">${t?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="tagToActivityLink" action="create" params="['activity.id': activityInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'tagToActivityLink.label', default: 'TagToActivityLink')])}</g:link>
</li>
</ul>

</div>

<div class="fieldcontain ${hasErrors(bean: activityInstance, field: 'taskLinks', 'error')} ">
	<label for="taskLinks">
		<g:message code="activity.taskLinks.label" default="Task Links" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${activityInstance?.taskLinks?}" var="t">
    <li><g:link controller="taskToActivityLink" action="show" id="${t.id}">${t?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="taskToActivityLink" action="create" params="['activity.id': activityInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'taskToActivityLink.label', default: 'TaskToActivityLink')])}</g:link>
</li>
</ul>

</div>

grails-app/views/activity/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'activity.label', default: 'Activity')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
                <ckeditor:resources/>
	</head>
	<body>
		<a href="#create-activity" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-activity" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${activityInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${activityInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:activityInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/activity/edit.gsp
<%@ page import="com.booleanworks.ring1.v1.Activity" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'activity.label', default: 'Activity')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
                <ckeditor:resources/>
	</head>
	<body>
		<a href="#edit-activity" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-activity" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${activityInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${activityInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:activityInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${activityInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/activity/index.gsp
<%@ page import="com.booleanworks.ring1.v1.Activity" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'activity.label', default: 'Activity')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-activity" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-activity" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="shortDescription" title="${message(code: 'activity.shortDescription.label', default: 'Short Description')}" />
					
						<g:sortableColumn property="longDescription" title="${message(code: 'activity.longDescription.label', default: 'Long Description')}" />
					
						<th><g:message code="activity.owner.label" default="Owner" /></th>
					
						<g:sortableColumn property="realWorkHours" title="${message(code: 'activity.realWorkHours.label', default: 'Real Work Hours')}" />
					
						<g:sortableColumn property="dateCreated" title="${message(code: 'activity.dateCreated.label', default: 'Date Created')}" />
					
						<g:sortableColumn property="lastUpdated" title="${message(code: 'activity.lastUpdated.label', default: 'Last Updated')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${activityInstanceList}" status="i" var="activityInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${activityInstance.id}">${fieldValue(bean: activityInstance, field: "shortDescription")}</g:link></td>
					
						<td>${fieldValue(bean: activityInstance, field: "longDescription")}</td>
					
						<td>${fieldValue(bean: activityInstance, field: "owner")}</td>
					
						<td>${fieldValue(bean: activityInstance, field: "realWorkHours")}</td>
					
						<td><g:formatDate date="${activityInstance.dateCreated}" /></td>
					
						<td><g:formatDate date="${activityInstance.lastUpdated}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${activityInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/activity/show.gsp
<%@ page import="com.booleanworks.ring1.v1.Activity" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'activity.label', default: 'Activity')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-activity" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-activity" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list activity">
			
				<g:if test="${activityInstance?.shortDescription}">
				<li class="fieldcontain">
					<span id="shortDescription-label" class="property-label"><g:message code="activity.shortDescription.label" default="Short Description" /></span>
					
						<span class="property-value" aria-labelledby="shortDescription-label"><g:fieldValue bean="${activityInstance}" field="shortDescription"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${activityInstance?.longDescription}">
				<li class="fieldcontain">
					<span id="longDescription-label" class="property-label"><g:message code="activity.longDescription.label" default="Long Description" /></span>
					
						<span class="property-value" aria-labelledby="longDescription-label"><g:fieldValue bean="${activityInstance}" field="longDescription"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${activityInstance?.owner}">
				<li class="fieldcontain">
					<span id="owner-label" class="property-label"><g:message code="activity.owner.label" default="Owner" /></span>
					
						<span class="property-value" aria-labelledby="owner-label"><g:link controller="person" action="show" id="${activityInstance?.owner?.id}">${activityInstance?.owner?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${activityInstance?.realWorkHours}">
				<li class="fieldcontain">
					<span id="realWorkHours-label" class="property-label"><g:message code="activity.realWorkHours.label" default="Real Work Hours" /></span>
					
						<span class="property-value" aria-labelledby="realWorkHours-label"><g:fieldValue bean="${activityInstance}" field="realWorkHours"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${activityInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="activity.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${activityInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${activityInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="activity.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${activityInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${activityInstance?.personLinks}">
				<li class="fieldcontain">
					<span id="personLinks-label" class="property-label"><g:message code="activity.personLinks.label" default="Person Links" /></span>
					
						<g:each in="${activityInstance.personLinks}" var="p">
						<span class="property-value" aria-labelledby="personLinks-label"><g:link controller="personToActivityLink" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${activityInstance?.tagLinks}">
				<li class="fieldcontain">
					<span id="tagLinks-label" class="property-label"><g:message code="activity.tagLinks.label" default="Tag Links" /></span>
					
						<g:each in="${activityInstance.tagLinks}" var="t">
						<span class="property-value" aria-labelledby="tagLinks-label"><g:link controller="tagToActivityLink" action="show" id="${t.id}">${t?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${activityInstance?.taskLinks}">
				<li class="fieldcontain">
					<span id="taskLinks-label" class="property-label"><g:message code="activity.taskLinks.label" default="Task Links" /></span>
					
						<g:each in="${activityInstance.taskLinks}" var="t">
						<span class="property-value" aria-labelledby="taskLinks-label"><g:link controller="taskToActivityLink" action="show" id="${t.id}">${t?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:activityInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${activityInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>