grails-app/domain/com/booleanworks/ring1/v1/FileChunk.groovy
package com.booleanworks.ring1.v1

class FileChunk {

    //static mapWith = "mongo"
    ////static searchable = true
    
    static  belongsTo = [fileItem : FileItem]
    
    
    static mapping = {
        autoTimestamp true
    }    
    
    static constraints = {
        chunkSize(nullable:false)
        chunkIndex(nullable:false)
    
        previousChunk(nullable:true)
        newtChunk(nullable:true)
    
        payload(nullable:false) 
        sha1Hash(nullable:false)
    
        dateCreated(nullable:true)
        lastUpdated (nullable:true)       
    }
    
    Long chunkSize
    Long chunkIndex
    
    FileChunk previousChunk
    FileChunk newtChunk
    
    byte[] payload 
    byte[] sha1Hash
    
    
    Date dateCreated
    Date lastUpdated  
    
    public String toString()
    {
        return "FileChunk[" + id + "]"
        //return "FileChunk[" + id + "], " + this.properties
    }
}

grails-app/controllers/com/booleanworks/ring1/v1/FileChunkController.groovy
package com.booleanworks.ring1.v1



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import grails.plugin.springsecurity.annotation.Secured

@Transactional(readOnly = true)
class FileChunkController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(["hasRole('SUPER_ADMIN')"])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond FileChunk.list(params), model:[fileChunkInstanceCount: FileChunk.count()]
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def show(FileChunk fileChunkInstance) {
        respond fileChunkInstance
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def create() {
        respond new FileChunk(params)
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def save(FileChunk fileChunkInstance) {
        if (fileChunkInstance == null) {
            notFound()
            return
        }

        if (fileChunkInstance.hasErrors()) {
            respond fileChunkInstance.errors, view:'create'
            return
        }

        fileChunkInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'fileChunkInstance.label', default: 'FileChunk'), fileChunkInstance.id])
                redirect fileChunkInstance
            }
            '*' { respond fileChunkInstance, [status: CREATED] }
        }
    }

    @Secured(["hasRole('SUPER_ADMIN')"])
    def edit(FileChunk fileChunkInstance) {
        respond fileChunkInstance
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def update(FileChunk fileChunkInstance) {
        if (fileChunkInstance == null) {
            notFound()
            return
        }

        if (fileChunkInstance.hasErrors()) {
            respond fileChunkInstance.errors, view:'edit'
            return
        }

        fileChunkInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'FileChunk.label', default: 'FileChunk'), fileChunkInstance.id])
                redirect fileChunkInstance
            }
            '*'{ respond fileChunkInstance, [status: OK] }
        }
    }

    @Transactional
    @Secured(["hasRole('SUPER_ADMIN')"])
    def delete(FileChunk fileChunkInstance) {

        if (fileChunkInstance == null) {
            notFound()
            return
        }

        fileChunkInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'FileChunk.label', default: 'FileChunk'), fileChunkInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'fileChunkInstance.label', default: 'FileChunk'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/fileChunk/_form.gsp
<%@ page import="com.booleanworks.ring1.v1.FileChunk" %>



<div class="fieldcontain ${hasErrors(bean: fileChunkInstance, field: 'chunkSize', 'error')} required">
	<label for="chunkSize">
		<g:message code="fileChunk.chunkSize.label" default="Chunk Size" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="chunkSize" type="number" value="${fileChunkInstance.chunkSize}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: fileChunkInstance, field: 'chunkIndex', 'error')} required">
	<label for="chunkIndex">
		<g:message code="fileChunk.chunkIndex.label" default="Chunk Index" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="chunkIndex" type="number" value="${fileChunkInstance.chunkIndex}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: fileChunkInstance, field: 'previousChunk', 'error')} ">
	<label for="previousChunk">
		<g:message code="fileChunk.previousChunk.label" default="Previous Chunk" />
		
	</label>
	<g:select id="previousChunk" name="previousChunk.id" from="${com.booleanworks.ring1.v1.FileChunk.list()}" optionKey="id" value="${fileChunkInstance?.previousChunk?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: fileChunkInstance, field: 'newtChunk', 'error')} ">
	<label for="newtChunk">
		<g:message code="fileChunk.newtChunk.label" default="Newt Chunk" />
		
	</label>
	<g:select id="newtChunk" name="newtChunk.id" from="${com.booleanworks.ring1.v1.FileChunk.list()}" optionKey="id" value="${fileChunkInstance?.newtChunk?.id}" class="many-to-one" noSelection="['null': '']"/>
</div>

<div class="fieldcontain ${hasErrors(bean: fileChunkInstance, field: 'payload', 'error')} required">
	<label for="payload">
		<g:message code="fileChunk.payload.label" default="Payload" />
		<span class="required-indicator">*</span>
	</label>
	<input type="file" id="payload" name="payload" />
</div>

<div class="fieldcontain ${hasErrors(bean: fileChunkInstance, field: 'sha1Hash', 'error')} required">
	<label for="sha1Hash">
		<g:message code="fileChunk.sha1Hash.label" default="Sha1 Hash" />
		<span class="required-indicator">*</span>
	</label>
	<input type="file" id="sha1Hash" name="sha1Hash" />
</div>

<div class="fieldcontain ${hasErrors(bean: fileChunkInstance, field: 'fileItem', 'error')} required">
	<label for="fileItem">
		<g:message code="fileChunk.fileItem.label" default="File Item" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="fileItem" name="fileItem.id" from="${com.booleanworks.ring1.v1.FileItem.list()}" optionKey="id" required="" value="${fileChunkInstance?.fileItem?.id}" class="many-to-one"/>
</div>

grails-app/views/fileChunk/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileChunk.label', default: 'FileChunk')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
                <ckeditor:resources/>
	</head>
	<body>
		<a href="#create-fileChunk" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-fileChunk" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${fileChunkInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${fileChunkInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:fileChunkInstance, action:'save']"  enctype="multipart/form-data">
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/fileChunk/edit.gsp
<%@ page import="com.booleanworks.ring1.v1.FileChunk" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileChunk.label', default: 'FileChunk')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
                <ckeditor:resources/>
	</head>
	<body>
		<a href="#edit-fileChunk" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-fileChunk" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${fileChunkInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${fileChunkInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:fileChunkInstance, action:'update']" method="PUT"  enctype="multipart/form-data">
				<g:hiddenField name="version" value="${fileChunkInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/fileChunk/index.gsp
<%@ page import="com.booleanworks.ring1.v1.FileChunk" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileChunk.label', default: 'FileChunk')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-fileChunk" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-fileChunk" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="chunkSize" title="${message(code: 'fileChunk.chunkSize.label', default: 'Chunk Size')}" />
					
						<g:sortableColumn property="chunkIndex" title="${message(code: 'fileChunk.chunkIndex.label', default: 'Chunk Index')}" />
					
						<th><g:message code="fileChunk.previousChunk.label" default="Previous Chunk" /></th>
					
						<th><g:message code="fileChunk.newtChunk.label" default="Newt Chunk" /></th>
					
						<g:sortableColumn property="payload" title="${message(code: 'fileChunk.payload.label', default: 'Payload')}" />
					
						<g:sortableColumn property="sha1Hash" title="${message(code: 'fileChunk.sha1Hash.label', default: 'Sha1 Hash')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${fileChunkInstanceList}" status="i" var="fileChunkInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${fileChunkInstance.id}">${fieldValue(bean: fileChunkInstance, field: "chunkSize")}</g:link></td>
					
						<td>${fieldValue(bean: fileChunkInstance, field: "chunkIndex")}</td>
					
						<td>${fieldValue(bean: fileChunkInstance, field: "previousChunk")}</td>
					
						<td>${fieldValue(bean: fileChunkInstance, field: "newtChunk")}</td>
					
						<td>${fieldValue(bean: fileChunkInstance, field: "payload")}</td>
					
						<td>${fieldValue(bean: fileChunkInstance, field: "sha1Hash")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${fileChunkInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/fileChunk/show.gsp
<%@ page import="com.booleanworks.ring1.v1.FileChunk" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'fileChunk.label', default: 'FileChunk')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-fileChunk" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-fileChunk" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list fileChunk">
			
				<g:if test="${fileChunkInstance?.chunkSize}">
				<li class="fieldcontain">
					<span id="chunkSize-label" class="property-label"><g:message code="fileChunk.chunkSize.label" default="Chunk Size" /></span>
					
						<span class="property-value" aria-labelledby="chunkSize-label"><g:fieldValue bean="${fileChunkInstance}" field="chunkSize"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileChunkInstance?.chunkIndex}">
				<li class="fieldcontain">
					<span id="chunkIndex-label" class="property-label"><g:message code="fileChunk.chunkIndex.label" default="Chunk Index" /></span>
					
						<span class="property-value" aria-labelledby="chunkIndex-label"><g:fieldValue bean="${fileChunkInstance}" field="chunkIndex"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileChunkInstance?.previousChunk}">
				<li class="fieldcontain">
					<span id="previousChunk-label" class="property-label"><g:message code="fileChunk.previousChunk.label" default="Previous Chunk" /></span>
					
						<span class="property-value" aria-labelledby="previousChunk-label"><g:link controller="fileChunk" action="show" id="${fileChunkInstance?.previousChunk?.id}">${fileChunkInstance?.previousChunk?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileChunkInstance?.newtChunk}">
				<li class="fieldcontain">
					<span id="newtChunk-label" class="property-label"><g:message code="fileChunk.newtChunk.label" default="Newt Chunk" /></span>
					
						<span class="property-value" aria-labelledby="newtChunk-label"><g:link controller="fileChunk" action="show" id="${fileChunkInstance?.newtChunk?.id}">${fileChunkInstance?.newtChunk?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileChunkInstance?.payload}">
				<li class="fieldcontain">
					<span id="payload-label" class="property-label"><g:message code="fileChunk.payload.label" default="Payload" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileChunkInstance?.sha1Hash}">
				<li class="fieldcontain">
					<span id="sha1Hash-label" class="property-label"><g:message code="fileChunk.sha1Hash.label" default="Sha1 Hash" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileChunkInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="fileChunk.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${fileChunkInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileChunkInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="fileChunk.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${fileChunkInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${fileChunkInstance?.fileItem}">
				<li class="fieldcontain">
					<span id="fileItem-label" class="property-label"><g:message code="fileChunk.fileItem.label" default="File Item" /></span>
					
						<span class="property-value" aria-labelledby="fileItem-label"><g:link controller="fileItem" action="show" id="${fileChunkInstance?.fileItem?.id}">${fileChunkInstance?.fileItem?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:fileChunkInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${fileChunkInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>